language: node_js
node_js:
  - '15'
  - '14'
  - '12'
  - '10'
  - '8'
os:
  - linux
  - osx
  - windows
script:
  - if [ "${TRAVIS_NODE_VERSION}" == "14" ] && [ "${TRAVIS_OS_NAME}" == linux ];
    then npm run lint; fi
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
